const fs = require("fs");
const lines = [
"/* SyncParagraph — cinema teleprompter",
"   Scale-based hierarchy: font-size never changes so layout is stable.",
"   JS only sets data-distance; CSS handles all visuals via transitions. */",
"",
".container {",
"  position: relative;",
"  flex: 1;",
"  overflow: hidden;",
"  mask-image: linear-gradient(",
"    to bottom,",
"    transparent  0%,",
"    black       10%,",
"    black       90%,",
"    transparent 100%",
"  );",
"  -webkit-mask-image: linear-gradient(",
"    to bottom,",
"    transparent  0%,",
"    black       10%,",
"    black       90%,",
"    transparent 100%",
"  );",
"}",
"",
".inner {",
"  padding-block: 50vh;",
"  will-change: transform;",
"}",
"",
"/* Fixed geometry — scale() changes visuals without shifting layout */",
".line {",
"  text-align: center;",
"  padding: 2px 16px;",
"  font-size: 0.82rem;",
"  line-height: 1.6;",
"  color: inherit;",
"  transform-origin: center center;",
"  transition:",
"    transform    0.55s cubic-bezier(0.22, 1, 0.36, 1),",
"    opacity      0.55s ease,",
"    font-weight  0.3s  ease,",
"    color        0.55s ease,",
"    text-shadow  0.55s ease;",
"}",
"",
".line[data-distance=\"0\"] {",
"  transform:   scale(1.48);",
"  opacity:     1;",
"  font-weight: 650;",
"}",
".line[data-distance=\"1\"] {",
"  transform:   scale(1.12);",
"  opacity:     0.68;",
"  font-weight: 400;",
"}",
".line[data-distance=\"2\"] {",
"  transform: scale(0.96);",
"  opacity:   0.42;",
"}",
".line[data-distance=\"3\"] {",
"  transform: scale(0.88);",
"  opacity:   0.24;",
"}",
".line[data-distance=\"4\"] {",
"  transform: scale(0.83);",
"  opacity:   0.13;",
"}",
".line[data-distance=\"5\"] {",
"  transform: scale(0.79);",
"  opacity:   0.07;",
"}",
".line[data-distance=\"6\"] {",
"  transform: scale(0.76);",
"  opacity:   0.035;",
"}",
".line[data-distance=\"7\"] {",
"  transform: scale(0.74);",
"  opacity:   0.015;",
"}",
".line[data-distance=\"8\"] {",
"  transform: scale(0.73);",
"  opacity:   0.005;",
"}",
".line[data-distance=\"9\"] {",
"  transform: scale(0.72);",
"  opacity:   0;",
"}",
"",
".dark .line[data-distance=\"0\"] {",
"  color:       #ddeeff;",
"  text-shadow: 0 0 20px rgba(120, 200, 255, 0.5);",
"}",
".dark .line[data-distance=\"1\"] {",
"  color: #aac8e8;",
"}",
".dark .line[data-distance=\"2\"],",
".dark .line[data-distance=\"3\"] {",
"  color: #7a9cc0;",
"}",
];
fs.writeFileSync("components/SyncParagraph.module.css", lines.join("\n") + "\n");
console.log("Written", lines.length, "lines");

